# Generated by Django 4.1.6 on 2023-02-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('numero_oab', models.IntegerField()),
                ('especialidade', models.CharField(choices=[('DC', 'Direito Civil'), ('DP', 'Direito Previdenciário'), ('DT', 'Direito do Trabalho'), ('PE', 'Direito Penal'), ('DD', 'Direito Digital'), ('DA', 'Direito Administrativo'), ('DE', 'Direito Empresarial'), ('TR', 'Direito Tributário'), ('AG', 'Direito Agrário'), ('CO', 'Direito Constitucional')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('rg', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=200)),
            ],
        ),
    ]
