# Generated by Django 4.1.6 on 2025-01-21 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escritorio', '0003_advogado_email_advogado_telefone_cliente_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='rg',
        ),
        migrations.AlterField(
            model_name='advogado',
            name='telefone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('AB', 'Aberto'), ('EM', 'Em andamento'), ('FI', 'Finalizado')], max_length=2)),
                ('advogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='escritorio.advogado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='escritorio.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('descricao', models.CharField(max_length=255)),
                ('advogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='escritorio.advogado')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escritorio.cliente')),
            ],
        ),
    ]
